# Agentic workflow configuration
planning_agent:
  model: "gpt-4o-mini"
  temperature: 0.1
  max_tokens: 1000
  timeout_seconds: 30


parallel_search:
  enabled: true
  concurrent_searches: 3
  search_types:
    - "general_guidance"
    - "penalty_research" 
    - "current_precedents"
  timeout_seconds: 60

assessment:
  model: "gpt-4o"
  temperature: 0.1
  max_tokens: 3000
  timeout_seconds: 90