# AI model configuration
openai:
  thinking_model: 'gpt-4o'
  slim_model: 'gpt-4o-mini'
  embedding_model: 'text-embedding-3-small'
  temperature: 0.1
  max_tokens: 2000

langchain:
  tracing_enabled: true
  project_name: 'federal-ethics-chatbot'

web_search:
  provider: 'tavily'
  max_results: 3
  search_depth: 'advanced'
  government_domains:
    - 'osg.gov'
    - 'oge.gov'
    - 'ethics.gov'
    - 'gsa.gov'
