# Data processing configuration
documents:
  data_directory: 'data'
  supported_formats:
    - 'pdf'
    - 'txt'
    - 'md'

evaluation:
  test_dataset_path: 'eval/fixtures/test_dataset.json'

text_splitting:
  strategy: 'recursive_character'
  chunk_size: 750
  chunk_overlap: 0
  length_function: 'tiktoken'

semantic_splitting:
  buffer_size: 1
  breakpoint_percentile_threshold: 95

document_loader:
  pdf_loader: 'pymupdf'
  extract_images: false
  extract_tables: true
