# Data processing configuration
documents:
  data_directory: 'data'
  supported_formats:
    - 'pdf'
    - 'txt'
    - 'md'

evaluation:
  test_dataset_path: 'eval/fixtures/test_dataset_markdown.json'

text_splitting:
  strategy: 'recursive_character'
  chunk_size: 1200
  chunk_overlap: 200
  length_function: 'tiktoken'

semantic_splitting:
  buffer_size: 1
  breakpoint_percentile_threshold: 95

# Chunking strategy selection
chunking:
  default_strategy: 'character' # 'character' or 'semantic'
  generate_both_collections: true # Generate both character and semantic collections

document_loader:
  pdf_loader: 'pymupdf'
  extract_images: false
  extract_tables: true
