# Data processing configuration
documents:
  data_directory: "./data"
  ethics_pdf_filename: "Compilation of Federal Ethics Laws (2025).pdf"
  supported_formats:
    - "pdf"
    - "txt"
    - "md"

text_splitting:
  strategy: "recursive_character" 
  chunk_size: 750
  chunk_overlap: 0
  length_function: "tiktoken"
  tiktoken_model: "gpt-4o"

document_loader:
  pdf_loader: "pymupdf"
  extract_images: false
  extract_tables: true