# Vector database configuration
qdrant:
  url: "memory"  # Default to in-memory, override with QDRANT_URL env var
  collections:
    character_chunks: "ethics_knowledge_index"  # Original character-based chunks
    semantic_chunks: "ethics_semantic_index"    # New semantic chunks
  embedding_dimension: 1536
  distance_metric: "cosine"

retrieval:
  top_k: 5
  score_threshold: 0.7
  rerank_enabled: false

indexing:
  batch_size: 100
  parallel_workers: 4